#Language: English
isSlimeChunk: "&aThe chunk is a slime chunk!"
notSlimeChunk: "&cThe chunk is not a slime chunk..."
reloadSuccess: "&6SlimeChunkChecker Plugin reloaded."
noPermission: "&4You don't have the permission to do this, sorry."
notPlayer: "&cYou must be a player to execute this command!"
versionCheck: true

#Language: 繁體中文
#isSlimeChunk: "&a此區塊是一個史萊姆區塊!"
#notSlimeChunk: "&c這個區塊不是一個史萊姆區塊..."
#reloadSuccess: "&6SlimeChunkChecker 插件已經重新讀取"
#noPermission: "&4你沒有權限使用此指令。"
#notPlayer: "&c你必須是玩家才可以使用此指令!"